name: "Code static analysis"

on: [push]

jobs:
  rector:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out package code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - name: Composer install
        run: composer install

      - name: Run Rector
        run: vendor/bin/rector --dry-run